### ISSUE TITLE
Symfony 4 Support

### ISSUE THREAD

**Issue by emnsen** [VincentChalnot/SidusEAVModelBundle#28]
Will it be symfony 4 support?

Regards.

**Comment by VincentChalnot** [comment]
Hello,
I don't know but it's worth testing it. I don't have any Symfony 4 projects for the moment.
It should work fine though.

**Comment by emnsen** [comment]
I will try as soon as possible, I will write here again about the result.
Thanks for the answer.

**Comment by burntblark** [comment]
Hi @emnsen. Have you tried this and was it possible? If yes, kindly share. I tried with Symfony 4.3 and I haven't been successful. I mostly had issues with compatibility with other module.

**Comment by emnsen** [comment]
Hello @burntblark no, I didn't try. I can't remember exactly, it was a long time ago, I think I solved my problem without this bundle.

**Comment by lifo101** [comment]
@burntblark no, it does not work with symfony4. I tried with 4.4 and composer does not like the dependencies that this bundle requires.
