### ISSUE TITLE
Unable to replace alias "sidus_eav_model.denormalizer.data" with actual definition "Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer".

### ISSUE THREAD

**Issue by jhfyang** [VincentChalnot/SidusEAVModelBundle#29]
I am getting an error after installation.

I am getting this error 

`Unable to replace alias "sidus_eav_model.denormalizer.data" with actual definition "Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer".`

with: 
`You have requested a non-existent service "Sidus\EAVModelBundle\Serializer\Denormalizer\EAVDataDenormalizer".`

I do not see what I have done wrong, I have configured the bundle in config.yaml and also registered in AppKernel class

**Comment by VincentChalnot** [comment]
Hello, have you tried to update to last version? I think I fixed this issue in later releases.

What version of Symfony are you using?

**Comment by nirmalan** [comment]
I have to problem too.
Using the latest version of this Repo and Symfony 3.4.

Could get this running by commenting the services definitions in
`vendor/sidus/eav-model-bundle/Resources/config/services/deprecated.yml`

**Comment by VincentChalnot** [comment]
Oh, I see what's the problem here. Quick solution is to enable Symfony's serializer and activate it's support in this bundle:
https://vincentchalnot.github.io/SidusEAVModelBundle/Documentation/10-serialize.html
I'll release a patch in the next release.

**Comment by VincentChalnot** [comment]
This should be fixed in v1.2.20
