### ISSUE TITLE
Installation Failed

### ISSUE THREAD

**Issue by sulaman0** [VincentChalnot/SidusEAVModelBundle#33]
When I'm trying to install SidusEAV Bundle then, Symfony flex version incompatibility error comes up.

Please have a look at the screenshot. 
![image](https://user-images.githubusercontent.com/30592487/58798722-cc853900-861c-11e9-8f83-af0bcc891c1e.png)

**Comment by VincentChalnot** [comment]
Hello,
The compatibility with Symfony 4.0 has never been tested, you can override this message by adding "symfony/symfony": "*" in the "replace" section of the composer.json.

**Comment by sulaman0** [comment]
Hello,

Thanks for the help. 
I appreciate your quick response. :-)
